name: Build Configs

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  Build-Default:
    name: Build Default Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [H32]
    steps:
    - name: Compile firmware
      uses: actions/checkout@v3
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      id: build_configs
      run: |
        echo "filename=Default-NoProbe-${AQUILA_VER}.bin" >> $GITHUB_OUTPUT
        cp firmware/Configuration\ Files/Aquila\ Templates/Default-NoProbe/Configuration.h firmware/Sources/Marlin/Configuration.h
        cp firmware/Configuration\ Files/Aquila\ Templates/Default-NoProbe/Configuration_adv.h firmware/Sources/Marlin/Configuration_adv.h
        cd firmware/Debug
        make all
      env:
        AQUILA_VER: ${{ matrix.chip }}
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: firmware/Debug/firmware.bin
        name: Upload Release Asset
        tag_name: ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

